Repository luucasaraujoo/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: Análise

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#8 Integrar testes v1.0
  src/src/testes_jogar.py
  src/testes_inic.py
Labels: Testes

#9 Gerar release v1.0
  src/jogovelha.py
  src/src/testes_jogar.py
  src/testes_inic.py
Labels: Operações

#16 Integrar requisitos v1.1
  docs/requisitos.md
Labels: Análise

#17 Implementando teste arquitetura
  docs/arquitetura.md
Labels: Arquitetura

#15 integrar teste v1.1
  src/jogovelha.py
  src/testes_inic.py
Labels: Testes

#18 Testar inicialização do tabuleiro. v1.1
  src/jogovelha.py
Labels: Programação
